name: Identity WG submission
description: Form for submitting use cases, problem statements, threats, or solutions.
title: "SUBMISSION TYPE - Title"
labels: ["use case"]
assignees: 
  - naomi-wash
  - carmen-viloria
  - rohinlohe
body:
  - type: markdown
    attributes:
      value: Please replace `SUBMISSION TYPE` in the title above with your chosen submission category followed by your submission title.
  - type: dropdown
    id: submission_category
    attributes:
      label: Submission Category
      description: Pick the option closest to the type of request you have.
      multiple: false
      options:
        - Use Case or Problem Statement
        - Requirement or Threat (e.g., sybil attack, privacy leak)
        - Solution (an existing standard or a solution the contributor has created)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide the details of your submission here.
    validations:
      required: true
  - type: input
    id: reference_link
    attributes:
      label: Reference Link
      description: Optional link to a standards page, documentation, or relevant resource.
      placeholder: https://...
    validations:
      required: false
  - type: input
    id: affiliation
    attributes:
      label: Organization or Affiliation 
      description: Please share your organization or relevant affiliation. 
    validations:
      required: true
